language: python
sudo: required
matrix:
  include:
  - python: '3.6'
  - python: '3.7'
    dist: xenial
  - os: windows
    language: bash
    python: 3.7
    before_install:
      - export TRAVIS_PYTHON_VERSION=3.7
      - choco install python --version $TRAVIS_PYTHON_VERSION
      - export PATH="/C/Python37:/C/Python37/Scripts:$PATH"
install:
  - pip install nox
script:
  - pyenv global $TRAVIS_PYTHON_VERSION
  - nox --non-interactive
cache:
  pip: true
