language: python
sudo: required
matrix:
  include:
  - python: '3.6'
    env: NOXSESSION=unittests,docs,lint-3.6
  - python: '3.7'
    env: NOXSESSION=unittests,docs,lint-3.7
    dist: xenial
install:
  - pip install nox
script:
  - nox --non-interactive
cache:
  pip: true
